export type LanguageCode = 'en' | 'hi' | 'ta' | 'kn' | 'ml';

export interface LanguageInfo {
  code: LanguageCode;
  name: string;
  nativeName: string;
  state: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English', state: 'National Standard' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', state: 'Tamil Nadu' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', state: 'Karnataka' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', state: 'Kerala' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', state: 'National / Northern States' },
];

export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Brand & Header
    'app.name': 'LandSync',
    'app.tagline': 'One Parcel. One Connected View. Complete Trust.',
    'app.sih': 'Smart India Hackathon 2026 (SIH26014) • DPI for Land Governance',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.gis': 'GIS Cadastral Map',
    'nav.land_dna': 'Land DNA Intelligence',
    'nav.spatial_analytics': 'Spatial Analytics',
    'nav.civic_services': 'Civic & Infrastructure',
    'nav.state_configuration': 'State Configuration (Phase 10)',
    'nav.state_comparison': 'State Comparison & Benchmarking',
    'nav.state_onboarding': 'State Onboarding Wizard',
    'nav.documents': 'Document OCR & Verification',
    'nav.applications': 'My Applications',
    'nav.data_sharing': 'Consent & Data Sharing',
    'nav.users': 'User Management',
    'nav.system': 'System Overview',
    'nav.notifications': 'Notifications',
    'nav.profile': 'Profile & Settings',
    'nav.logout': 'Sign Out',

    // Roles & Context
    'role.citizen': 'Citizen',
    'role.officer': 'Nodal Officer',
    'role.admin': 'System Administrator',
    'context.rural': 'Rural Cadastral Context',
    'context.urban': 'Urban Municipal Context',
    
    // Common Actions & Buttons
    'action.search': 'Search Parcel / ULPIN',
    'action.filter': 'Filter',
    'action.export': 'Export Report',
    'action.view_details': 'View 360° Profile',
    'action.save': 'Save Configuration',
    'action.apply': 'Apply Changes',
    'action.reset': 'Reset Defaults',
    'action.download_pdf': 'Download PDF Record',
    'action.submit_request': 'Submit Application',
    'action.normalize_record': 'Normalize Source Record',
    'action.run_quality_check': 'Run Data Quality Audit',
    'action.run_readiness': 'Calculate Readiness Score',

    // Parcel & Terminology
    'term.ulpin': 'Unique Land Parcel Identification Number (ULPIN)',
    'term.survey_no': 'Survey Number / Sub-Division',
    'term.owner': 'Registered Owner',
    'term.extent': 'Area / Extent',
    'term.land_use': 'Land Use / Classification',
    'term.patta': 'Patta / Chitta (Ownership Record)',
    'term.rtc': 'RTC / Pahani (Record of Rights)',
    'term.thandaper': 'Thandaper (Land Account)',
    'term.satbara': '7/12 Satbara Extract',
    'term.original_doc_notice': 'Original document language preserved. Official translation preview generated by LandSync Engine.',
    
    // State Config Engine
    'state.title': 'National Scalability & State Configuration Engine',
    'state.subtitle': 'Adapting LandSync across all 28 States and 8 UTs with dynamic field mapping, local units, and regional workflows.',
    'state.readiness_ready': 'Deployment Ready',
    'state.readiness_configured': 'Configured',
    'state.readiness_partial': 'Partially Ready',
    'state.readiness_not_ready': 'Needs Onboarding',

    // Status
    'status.active': 'Active',
    'status.pending': 'Pending',
    'status.approved': 'Approved',
    'status.rejected': 'Rejected',
    'status.verified': 'Verified',
    'status.flagged': 'Anomaly Flagged'
  },

  ta: {
    // Brand & Header
    'app.name': 'லேண்சின்க் (LandSync)',
    'app.tagline': 'ஒரு நிலப்பரப்பு. ஒரு ஒருங்கிணைந்த பார்வை. முழுமையான நம்பிக்கை.',
    'app.sih': 'ஸ்மார்ட் இந்தியா ஹேக்கத்தான் 2026 • நில நிர்வாகத்திற்கான தேசிய டிஜிட்டல் உள்கட்டமைப்பு',
    
    // Navigation
    'nav.dashboard': 'முகப்பு பலகை',
    'nav.gis': 'ஜி.ஐ.எஸ் நில வரைபடம்',
    'nav.land_dna': 'நில டி.என்.ஏ நுண்ணறிவு',
    'nav.spatial_analytics': 'இடஞ்சார்ந்த பகுப்பாய்வு',
    'nav.civic_services': 'நகராட்சி மற்றும் உள்கட்டமைப்பு',
    'nav.state_configuration': 'மாநில கட்டமைப்பு இயந்திரம் (பகுதி 10)',
    'nav.state_comparison': 'மாநில ஒப்பீடு மற்றும் தரம்',
    'nav.state_onboarding': 'புதிய மாநில பதிவு வழிகாட்டி',
    'nav.documents': 'ஆவண சரிபார்ப்பு மற்றும் OCR',
    'nav.applications': 'எனது விண்ணப்பங்கள்',
    'nav.data_sharing': 'தரவு பகிர்வு மற்றும் ஒப்புதல்',
    'nav.users': 'பயனர் மேலாண்மை',
    'nav.system': 'அமைப்பு கண்ணோட்டம்',
    'nav.notifications': 'அறிவிப்புகள்',
    'nav.profile': 'சுயவிவரம் மற்றும் அமைப்புகள்',
    'nav.logout': 'வெளியேறு',

    // Roles & Context
    'role.citizen': 'குடிமகன்',
    'role.officer': 'வருவாய் துறை அதிகாரி',
    'role.admin': 'நிர்வாகி',
    'context.rural': 'கிராமப்புற பட்டா சூழல்',
    'context.urban': 'நகர்ப்புற திட்ட சூழல்',
    
    // Common Actions & Buttons
    'action.search': 'நில எண் / ULPIN தேடுக',
    'action.filter': 'வடிகட்டுக',
    'action.export': 'அறிக்கையை பதிவிறக்கு',
    'action.view_details': 'முழு விவரம் காண்க',
    'action.save': 'அமைப்பை சேமி',
    'action.apply': 'மாற்றங்களை பயன்படுத்து',
    'action.reset': 'மீட்டமைக்க',
    'action.download_pdf': 'PDF ஆவணம் பதிவிறக்கு',
    'action.submit_request': 'விண்ணப்பம் சமர்ப்பிக்கவும்',
    'action.normalize_record': 'மாநில பதிவை தரப்படுத்துக',
    'action.run_quality_check': 'தர சோதனையை இயக்கு',
    'action.run_readiness': 'தயார்நிலை மதிப்பெண் கணக்கிடு',

    // Parcel & Terminology
    'term.ulpin': 'தனித்துவ நில அடையாள எண் (ULPIN)',
    'term.survey_no': 'புல எண் மற்றும் உட்பிரிவு',
    'term.owner': 'பதிவு செய்யப்பட்ட உரிமையாளர்',
    'term.extent': 'பரப்பளவு (ஏக்கர் / சென்ட் / குழி)',
    'term.land_use': 'நில பயன்பாட்டு வகைப்பாடு',
    'term.patta': 'பட்டா / சிட்டா (உரிமை ஆவணம்)',
    'term.rtc': 'ஆர்டிசி / பஹானி',
    'term.thandaper': 'தாண்டபேர் நில கணக்கு',
    'term.satbara': '7/12 சத்Groupபாரா பதிவு',
    'term.original_doc_notice': 'அசல் ஆவண மொழி பாதுகாக்கப்பட்டுள்ளது. LandSync இயந்திரத்தால் மொழிபெயர்ப்பு முன்னோட்டம் உருவாக்கப்பட்டது.',
    
    // State Config Engine
    'state.title': 'தேசிய அளவிடுதல் மற்றும் மாநில கட்டமைப்பு இயந்திரம்',
    'state.subtitle': 'டைனமிக் புல மேப்பிங், உள்ளூர் அலகுகள் மற்றும் பிராந்திய பணிப்பாய்வுகளுடன் அனைத்து 28 மாநிலங்களிலும் லேண்சின்க் செயல்படுகிறது.',
    'state.readiness_ready': 'பயன்பாட்டுக்கு தயார் (Deployment Ready)',
    'state.readiness_configured': 'கட்டமைக்கப்பட்டது',
    'state.readiness_partial': 'பகுதி தயார்நிலை',
    'state.readiness_not_ready': 'பதிவு தேவை',

    // Status
    'status.active': 'செயலில் உள்ளது',
    'status.pending': 'நிலுவையில் உள்ளது',
    'status.approved': 'ஒப்புதல் அளிக்கப்பட்டது',
    'status.rejected': 'நிராகரிக்கப்பட்டது',
    'status.verified': 'சரிபார்க்கப்பட்டது',
    'status.flagged': 'சிக்கல் கண்டறியப்பட்டது'
  },

  kn: {
    // Brand & Header
    'app.name': 'ಲ್ಯಾಂಡ್‌ಸಿಂಕ್ (LandSync)',
    'app.tagline': 'ಒಂದು ಭೂಮಿ. ಒಂದು ಸಮಗ್ರ ನೋಟ. ಸಂಪೂರ್ಣ ವಿಶ್ವಾಸ.',
    'app.sih': 'ಸ್ಮಾರ್ಟ್ ಇಂಡಿಯಾ ಹ್ಯಾಕಥಾನ್ 2026 • ಭೂ ಆಡಳಿತಕ್ಕಾಗಿ ರಾಷ್ಟ್ರೀಯ ಡಿಜಿಟಲ್ ಸಾರ್ವಜನಿಕ ಮೂಲಸೌಕರ್ಯ',
    
    // Navigation
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.gis': 'ಜಿ.ಐ.ಎಸ್ ನಕ್ಷೆ',
    'nav.land_dna': 'ಭೂಮಿ ಡಿ.ಎನ್.ಎ ಬುದ್ಧಿಮತ್ತೆ',
    'nav.spatial_analytics': 'ಪ್ರಾದೇಶಿಕ ವಿಶ್ಲೇಷಣೆ',
    'nav.civic_services': 'ನಾಗರಿಕ ಮತ್ತು ಮೂಲಸೌಕರ್ಯ',
    'nav.state_configuration': 'ರಾಜ್ಯ ಸಂರಚನಾ ಎಂಜಿನ್ (ಹಂತ 10)',
    'nav.state_comparison': 'ರಾಜ್ಯಗಳ ಹೋಲಿಕೆ',
    'nav.state_onboarding': 'ಹೊಸ ರಾಜ್ಯ ಆನ್‌ಬೋರ್ಡಿಂಗ್',
    'nav.documents': 'ದಾಖಲೆ ಪರಿಶೀಲನೆ (OCR)',
    'nav.applications': 'ನನ್ನ ಅರ್ಜಿಗಳು',
    'nav.data_sharing': 'ಡೇಟಾ ಹಂಚಿಕೆ ಮತ್ತು ಒಪ್ಪಿಗೆ',
    'nav.users': 'ಬಳಕೆದಾರರ ನಿರ್ವಹಣೆ',
    'nav.system': 'ವ್ಯವಸ್ಥೆಯ ಅವಲೋಕನ',
    'nav.notifications': 'ಸೂಚನೆಗಳು',
    'nav.profile': 'ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'nav.logout': 'ನಿರ್ಗಮಿಸಿ',

    // Roles & Context
    'role.citizen': 'ನಾಗರಿಕ',
    'role.officer': 'ಕಂದಾಯ ಅಧಿಕಾರಿ',
    'role.admin': 'ವ್ಯವಸ್ಥಾಪಕ',
    'context.rural': 'ಗ್ರಾಮೀಣ ಆರ್‌ಟಿಸಿ ಸಂದರ್ಭ',
    'context.urban': 'ನಗರ ಸಭೆ ಸಂದರ್ಭ',
    
    // Common Actions & Buttons
    'action.search': 'ಸರ್ವೆ ನಂಬರ್ / ULPIN ಹುಡುಕಿ',
    'action.filter': 'ಫಿಲ್ಟರ್',
    'action.export': 'ವರದಿ ಡೌನ್‌ಲೋಡ್',
    'action.view_details': 'ಸಂಪೂರ್ಣ ಮಾಹಿತಿ ನೋಡಿ',
    'action.save': 'ಸಂರಚನೆ ಉಳಿಸಿ',
    'action.apply': 'ಬದಲಾವಣೆ ಅನ್ವಯಿಸಿ',
    'action.reset': 'ಮರುಹೊಂದಿಸಿ',
    'action.download_pdf': 'ಪಿಡಿಎಫ್ ದಾಖಲೆ ಡೌನ್‌ಲೋಡ್',
    'action.submit_request': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'action.normalize_record': 'ರೆಕಾರ್ಡ್ ಗುಣಮಟ್ಟೀಕರಣ',
    'action.run_quality_check': 'ಡೇಟಾ ಗುಣಮಟ್ಟ ಪರೀಕ್ಷೆ',
    'action.run_readiness': 'ಸಿದ್ಧತೆ ಅಂಕ ಲೆಕ್ಕಾಚಾರ',

    // Parcel & Terminology
    'term.ulpin': 'ಅನನ್ಯ ಭೂಮಿ ಗುರುತಿನ ಸಂಖ್ಯೆ (ULPIN)',
    'term.survey_no': 'ಸರ್ವೆ ನಂಬರ್ ಮತ್ತು ಹಿಸ್ಸಾ',
    'term.owner': 'ನೋಂದಾಯಿತ ಮಾಲೀಕರು',
    'term.extent': 'ವಿಸ್ತೀರ್ಣ (ಎಕರೆ / ಗುಂಟೆ)',
    'term.land_use': 'ಭೂ ಬಳಕೆ ವಿಭಾಗ',
    'term.patta': 'ಪಟ್ಟಾ (ತಮಿಳುನಾಡು ಮಾದರಿ)',
    'term.rtc': 'ಆರ್‌ಟಿಸಿ / ಪಹಣಿ (ಭೂಮಿ ಹಕ್ಕುಗಳ ದಾಖಲೆ)',
    'term.thandaper': 'ತಾಂಡಪೇರ್ (ಕೇರಳ ಮಾದರಿ)',
    'term.satbara': '7/12 ಸಾತ್‌ಬಾರಾ ದಾಖಲೆ',
    'term.original_doc_notice': 'ಮೂಲ ದಾಖಲೆಯ ಭಾಷೆಯನ್ನು ಸಂರಕ್ಷಿಸಲಾಗಿದೆ.',
    
    // State Config Engine
    'state.title': 'ರಾಷ್ಟ್ರೀಯ ಸ್ಕೇಲೆಬಿಲಿಟಿ ಮತ್ತು ರಾಜ್ಯ ಸಂರಚನಾ ಎಂಜಿನ್',
    'state.subtitle': 'ಕರ್ನಾಟಕದ ಭೂಮಿ ಮತ್ತು ಕಾವೇರಿ 2.0 ನೊಂದಿಗೆ ಸುಲಭ ಏಕೀಕರಣ.',
    'state.readiness_ready': 'ಬಳಕೆಗೆ ಸಂಪೂರ್ಣ ಸಿದ್ಧ',
    'state.readiness_configured': 'ಸಂರಚಿಸಲಾಗಿದೆ',
    'state.readiness_partial': 'ಭಾಗಶಃ ಸಿದ್ಧ',
    'state.readiness_not_ready': 'ಆನ್‌ಬೋರ್ಡಿಂಗ್ ಅಗತ್ಯವಿದೆ',

    // Status
    'status.active': 'ಸಕ್ರಿಯ',
    'status.pending': 'ಬಾಕಿ ಇದೆ',
    'status.approved': 'ಅನುಮೋದಿಸಲಾಗಿದೆ',
    'status.rejected': 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    'status.verified': 'ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    'status.flagged': 'ಸಮಸ್ಯೆ ಪತ್ತೆಯಾಗಿದೆ'
  },

  ml: {
    // Brand & Header
    'app.name': 'ലാന്റ്സിങ്ക് (LandSync)',
    'app.tagline': 'ഒരു ഭൂമി. ഒരു ഏകീകൃത വീക്ഷണം. പൂർണ്ണ വിശ്വാസം.',
    'app.sih': 'സ്മാർട്ട് ഇന്ത്യ ഹാക്കത്തോൺ 2026 • ഡിജിറ്റൽ ലാൻഡ് പബ്ലിക് ഇൻഫ്രാസ്ട്രക്ചർ',
    
    // Navigation
    'nav.dashboard': 'ഡാഷ്‌ബോർഡ്',
    'nav.gis': 'ജി.ഐ.എസ് കാഡസ്ട്രൽ മാപ്പ്',
    'nav.land_dna': 'ലാൻഡ് ഡി.എൻ.എ ഇന്റലിജൻസ്',
    'nav.spatial_analytics': 'സ്പേഷ്യൽ അനലിറ്റിക്സ്',
    'nav.civic_services': 'മുനിസിപ്പൽ & പശ്ചാത്തല സൗകര്യങ്ങൾ',
    'nav.state_configuration': 'സംസ്ഥാന ക്രമീകരണ എഞ്ചിൻ (ഫേസ് 10)',
    'nav.state_comparison': 'സംസ്ഥാനങ്ങളുടെ താരതമ്യം',
    'nav.state_onboarding': 'സംസ്ഥാന ഓൺബോർഡിംഗ് വിസാർഡ്',
    'nav.documents': 'ഡോക്യുമെന്റ് പരിശോധന (OCR)',
    'nav.applications': 'എന്റെ അപേക്ഷകൾ',
    'nav.data_sharing': 'ഡാറ്റ പങ്കിടൽ സമ്മതം',
    'nav.users': 'ഉപയോക്തൃ മാനേജ്മെന്റ്',
    'nav.system': 'സിസ്റ്റം അവലോകനം',
    'nav.notifications': 'അറിയിപ്പുകൾ',
    'nav.profile': 'പ്രൊഫൈൽ & ക്രമീകരണങ്ങൾ',
    'nav.logout': 'ലോഗ് ഔട്ട്',

    // Roles & Context
    'role.citizen': 'പൗരൻ',
    'role.officer': 'റവന്യൂ ഓഫീസർ',
    'role.admin': 'അഡ്മിനിസ്ട്രേറ്റർ',
    'context.rural': 'ഗ്രാമീണ തണ്ടപ്പേര് പശ്ചാത്തലം',
    'context.urban': 'നഗരസഭാ പശ്ചാത്തലം',
    
    // Common Actions & Buttons
    'action.search': 'സർവേ നമ്പർ / ULPIN തിരയുക',
    'action.filter': 'ഫിൽട്ടർ',
    'action.export': 'റിപ്പോർട്ട് ഡൗൺലോഡ്',
    'action.view_details': '360° വിവരങ്ങൾ കാണുക',
    'action.save': 'കോൺഫിഗറേഷൻ സേവ് ചെയ്യുക',
    'action.apply': 'മാറ്റങ്ങൾ വരുത്തുക',
    'action.reset': 'റീസെറ്റ് ചെയ്യുക',
    'action.download_pdf': 'പി.ഡി.എഫ് ഡൗൺലോഡ്',
    'action.submit_request': 'അപേക്ഷ സമർപ്പിക്കുക',
    'action.normalize_record': 'ഡാറ്റ ഏകീകരിക്കുക',
    'action.run_quality_check': 'ഡാറ്റാ പരിശോധന നടത്തുക',
    'action.run_readiness': 'സന്നദ്ധതാ സ്കോർ കണക്കാക്കുക',

    // Parcel & Terminology
    'term.ulpin': 'ഭൂമി തിരിച്ചറിയൽ നമ്പർ (ULPIN)',
    'term.survey_no': 'സർവേ നമ്പറും സബ് ഡിവിഷനും',
    'term.owner': 'രജിസ്റ്റർ ചെയ്ത ഉടമ',
    'term.extent': 'വിസ്തീർണം (ഏക്കർ / സെന്റ് / ഹെക്ടർ)',
    'term.land_use': 'ഭൂമി ഉപയോഗ തരം',
    'term.patta': 'പട്ടയം (തമിഴ്നാട്)',
    'term.rtc': 'ആർ.ടി.സി (കർണാടക)',
    'term.thandaper': 'തണ്ടപ്പേര് (ഭൂമി അക്കൗണ്ട് നമ്പർ)',
    'term.satbara': '7/12 സാത്ബാര (മഹാരാഷ്ട്ര)',
    'term.original_doc_notice': 'യഥാർത്ഥ രേഖയുടെ ഭാഷ നിലനിർത്തിയിരിക്കുന്നു.',
    
    // State Config Engine
    'state.title': 'ദേശീയ സ്കേലബിലിറ്റിയും സംസ്ഥാന കോൺഫിഗറേഷൻ എഞ്ചിനും',
    'state.subtitle': 'കേരളത്തിന്റെ ഇ-രേഖയും പേളുമായി (PEARL) പൂർണ്ണമായി പൊരുത്തപ്പെടുന്നു.',
    'state.readiness_ready': 'സമ്പൂർണ്ണ സജ്ജം (Deployment Ready)',
    'state.readiness_configured': 'ക്രമീകരിച്ചു',
    'state.readiness_partial': 'ഭാഗികമായി സജ്ജം',
    'state.readiness_not_ready': 'ഓൺബോർഡിംഗ് ആവശ്യമാണ്',

    // Status
    'status.active': 'സജീവം',
    'status.pending': 'തീർപ്പുകൽപ്പിക്കാത്തത്',
    'status.approved': 'അംഗീകരിച്ചു',
    'status.rejected': 'നിരസിച്ചു',
    'status.verified': 'സ്ഥിരീകരിച്ചു',
    'status.flagged': 'പ്രശ്നം കണ്ടെത്തി'
  },

  hi: {
    // Brand & Header
    'app.name': 'लैंडसिंक (LandSync)',
    'app.tagline': 'एक भूखंड। एक एकीकृत दृष्टिकोण। पूर्ण विश्वास।',
    'app.sih': 'स्मार्ट इंडिया हैकथॉन 2026 • भूमि प्रशासन के लिए राष्ट्रीय डिजिटल सार्वजनिक अवसंरचना (DPI)',
    
    // Navigation
    'nav.dashboard': 'डैशबोर्ड',
    'nav.gis': 'जीआईएस भूकर मानचित्र',
    'nav.land_dna': 'लैंड डीएनए इंटेलिजेंस',
    'nav.spatial_analytics': 'स्थानिक विश्लेषण',
    'nav.civic_services': 'नागरिक एवं बुनियादी ढांचा',
    'nav.state_configuration': 'राज्य विन्यास इंजन (चरण 10)',
    'nav.state_comparison': 'राज्य तुलना और बेंचमार्किंग',
    'nav.state_onboarding': 'राज्य ऑनबोर्डिंग विज़ार्ड',
    'nav.documents': 'दस्तावेज़ ओसीआर एवं सत्यापन',
    'nav.applications': 'मेरे आवेदन',
    'nav.data_sharing': 'डेटा साझाकरण सहमति',
    'nav.users': 'उपयोगकर्ता प्रबंधन',
    'nav.system': 'सिस्टम अवलोकन',
    'nav.notifications': 'सूचनाएं',
    'nav.profile': 'प्रोफ़ाइल एवं सेटिंग्स',
    'nav.logout': 'साइन आउट',

    // Roles & Context
    'role.citizen': 'नागरिक',
    'role.officer': 'राजस्व अधिकारी',
    'role.admin': 'सिस्टम प्रशासक',
    'context.rural': 'ग्रामीण भूकर संदर्भ',
    'context.urban': 'शहरी नगरपालिका संदर्भ',
    
    // Common Actions & Buttons
    'action.search': 'खसरा / सर्वेक्षण सं. / ULPIN खोजें',
    'action.filter': 'फ़िल्टर',
    'action.export': 'रिपोर्ट निर्यात करें',
    'action.view_details': '360° विवरण देखें',
    'action.save': 'विन्यास सहेजें',
    'action.apply': 'परिवर्तन लागू करें',
    'action.reset': 'रीसेट करें',
    'action.download_pdf': 'पीडीएफ रिकॉर्ड डाउनलोड करें',
    'action.submit_request': 'आवेदन जमा करें',
    'action.normalize_record': 'रिकॉर्ड मानकीकृत करें',
    'action.run_quality_check': 'डेटा गुणवत्ता जांचें',
    'action.run_readiness': 'तत्परता स्कोर की गणना करें',

    // Parcel & Terminology
    'term.ulpin': 'विशिष्ट भूमि पार्सल पहचान संख्या (ULPIN)',
    'term.survey_no': 'खसरा / सर्वेक्षण संख्या',
    'term.owner': 'पंजीकृत भू-स्वामी',
    'term.extent': 'क्षेत्रफल / विस्तार (एकड़ / बीघा / कनाल)',
    'term.land_use': 'भूमि उपयोग वर्गीकरण',
    'term.patta': 'पट्टा / खतौनी (स्वामित्व अभिलेख)',
    'term.rtc': 'आरटीसी / जमाबंदी',
    'term.thandaper': 'थांडापेर (भूमि खाता)',
    'term.satbara': '7/12 सातबारा उद्धरण',
    'term.original_doc_notice': 'मूल दस्तावेज़ भाषा सुरक्षित है। LandSync इंजन द्वारा अनुवादित पूर्वावलोकन।',
    
    // State Config Engine
    'state.title': 'राष्ट्रीय मापनीयता और राज्य विन्यास इंजन',
    'state.subtitle': 'डायनामिक फ़ील्ड मैपिंग, स्थानीय इकाइयों और क्षेत्रीय वर्कफ़्लो के साथ पूरे भारत में अनुकूलनीय।',
    'state.readiness_ready': 'तैनाती हेतु तैयार (Deployment Ready)',
    'state.readiness_configured': 'विन्यासित',
    'state.readiness_partial': 'आंशिक रूप से तैयार',
    'state.readiness_not_ready': 'ऑनबोर्डिंग आवश्यक',

    // Status
    'status.active': 'सक्रिय',
    'status.pending': 'लंबित',
    'status.approved': 'स्वीकृत',
    'status.rejected': 'अस्वीकृत',
    'status.verified': 'सत्यापित',
    'status.flagged': 'विसंगति चिह्नित'
  }
};
